### ISSUE TITLE
[Feature Request]: On Demand Collecting

### ISSUE THREAD

**Issue by Drjacky** [asvid/RemoteLogger#2]
Is that possible to send the logcat only if the user asked for it? (pressed a button).
So, with this approach, we have their permission and also, we open and close the connection whenever there is something wrong only.

**Comment by asvid** [comment]
This tool was created to solve a very specific problem, of not having developer mode enabled during development and debugging - not really for app users to interact with it.
Maybe tools like Firebase or Sentry will work for you just fine, or you can try logging to file and sending it when the user clicks the button.
